language: java
sudo: false

env:
- SPRING_PROFILES_ACTIVE=ci

addons:
  chrome: stable

services:

jdk:
- oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/


before_script:
- ./gradlew npm_install -g @angular/cli

script:
- ./gradlew :frontend:lint
- ./gradlew :frontend:check
- ./gradlew :backend:test
- ./gradlew :backend:bootJar
- ./startServer.sh
- ./gradlew :frontend:e2e