language: java
sudo: false

env:
- SPRING_PROFILES_ACTIVE=ci

addons:
  chrome: stable

services:

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.gradle/nodejs/
  - frontend/node_modules
  - frontend/.gradle/


before_script:
- ./gradlew npm_install -g @angular/cli
- ./gradlew npm_run_webdriver

script:
- ./gradlew :frontend:lint
- ./gradlew :frontend:test
- ./gradlew :backend:test
- ./gradlew :backend:bootJar
- ./startServer.sh 0.0.1
- ./gradlew :frontend:e2e