/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.zuehlke.fullstack.ConnectZuehlke.apis.insight.dto.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CapabilityDriver
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T13:18:19.970506+01:00[Europe/Zurich]")
public class CapabilityDriver {

    @JsonProperty("Id")

    private Long id = null;

    @JsonProperty("Name")

    private String name = null;

    @JsonProperty("Description")

    private String description = null;

    @JsonProperty("SortOrder")

    private Integer sortOrder = null;

    @JsonProperty("ManagedSkills")

    private List<ManagedSkill> managedSkills = null;

    public CapabilityDriver id(Long id) {
        this.id = id;
        return this;
    }


    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CapabilityDriver name(String name) {
        this.name = name;
        return this;
    }


    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CapabilityDriver description(String description) {
        this.description = description;
        return this;
    }


    /**
     * Get description
     *
     * @return description
     **/
    @Schema(description = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public CapabilityDriver sortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }


    /**
     * Get sortOrder
     *
     * @return sortOrder
     **/
    @Schema(description = "")
    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public CapabilityDriver managedSkills(List<ManagedSkill> managedSkills) {
        this.managedSkills = managedSkills;
        return this;
    }

    public CapabilityDriver addManagedSkillsItem(ManagedSkill managedSkillsItem) {
        if (this.managedSkills == null) {
            this.managedSkills = new ArrayList<ManagedSkill>();
        }
        this.managedSkills.add(managedSkillsItem);
        return this;
    }

    /**
     * Get managedSkills
     *
     * @return managedSkills
     **/
    @Schema(description = "")
    public List<ManagedSkill> getManagedSkills() {
        return managedSkills;
    }

    public void setManagedSkills(List<ManagedSkill> managedSkills) {
        this.managedSkills = managedSkills;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CapabilityDriver capabilityDriver = (CapabilityDriver) o;
        return Objects.equals(this.id, capabilityDriver.id) &&
                Objects.equals(this.name, capabilityDriver.name) &&
                Objects.equals(this.description, capabilityDriver.description) &&
                Objects.equals(this.sortOrder, capabilityDriver.sortOrder) &&
                Objects.equals(this.managedSkills, capabilityDriver.managedSkills);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, name, description, sortOrder, managedSkills);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CapabilityDriver {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
        sb.append("    managedSkills: ").append(toIndentedString(managedSkills)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
