/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.zuehlke.fullstack.ConnectZuehlke.apis.insight.dto.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CapabilityExpert
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T13:18:19.970506+01:00[Europe/Zurich]")
public class CapabilityExpert {

    @JsonProperty("ExperiencePoints")

    private Double experiencePoints = null;
    @JsonProperty("ExperienceLevel")

    private ExperienceLevelEnum experienceLevel = null;
    @JsonProperty("Skill")

    private Skill skill = null;
    @JsonProperty("VertecId")

    private Long vertecId = null;
    @JsonProperty("Code")

    private String code = null;
    @JsonProperty("FirstName")

    private String firstName = null;
    @JsonProperty("LastName")

    private String lastName = null;
    @JsonProperty("FullName")

    private String fullName = null;
    @JsonProperty("DateOfBirth")

    private OffsetDateTime dateOfBirth = null;
    @JsonProperty("Citizenship")

    private String citizenship = null;
    @JsonProperty("IsOwner")

    private Boolean isOwner = null;
    @JsonProperty("Office")

    private Office office = null;
    @JsonProperty("WorkingPlace")

    private String workingPlace = null;
    @JsonProperty("Description")

    private String description = null;
    @JsonProperty("LinkedInProfileUrl")

    private String linkedInProfileUrl = null;
    @JsonProperty("XingProfileUrl")

    private String xingProfileUrl = null;
    @JsonProperty("TwitterProfileUrl")

    private String twitterProfileUrl = null;
    @JsonProperty("GitHubUrl")

    private String gitHubUrl = null;
    @JsonProperty("BitBucketUrl")

    private String bitBucketUrl = null;
    @JsonProperty("TwitterUrl")

    private String twitterUrl = null;
    @JsonProperty("YammerUrl")

    private String yammerUrl = null;
    @JsonProperty("StackoverflowProfileUrl")

    private String stackoverflowProfileUrl = null;
    @JsonProperty("LastUpdated")

    private OffsetDateTime lastUpdated = null;
    @JsonProperty("EntryDate")

    private OffsetDateTime entryDate = null;
    @JsonProperty("LeaveDate")

    private OffsetDateTime leaveDate = null;
    @JsonProperty("StartsIn")

    private String startsIn = null;
    @JsonProperty("Duration")

    private String duration = null;
    @JsonProperty("HomePhone")

    private String homePhone = null;
    @JsonProperty("MobilePhone")

    private String mobilePhone = null;
    @JsonProperty("BusinessPhone")

    private String businessPhone = null;
    @JsonProperty("Mail")

    private String mail = null;
    @JsonProperty("Location")

    private String location = null;
    @JsonProperty("Wants")

    private String wants = null;
    @JsonProperty("Qualification")

    private Qualification qualification = null;
    @JsonProperty("Superior")

    private EmployeeResult superior = null;
    @JsonProperty("JobProfile")

    private JobProfile jobProfile = null;
    @JsonProperty("Title")

    private String title = null;
    @JsonProperty("Graduation")

    private String graduation = null;
    @JsonProperty("Focus")

    private FocusEnum focus = null;
    @JsonProperty("FocusText")

    private String focusText = null;
    @JsonProperty("Assistance")

    private Assistance assistance = null;
    @JsonProperty("Company")

    private Company company = null;
    @JsonProperty("InternalRate")

    private Double internalRate = null;
    @JsonProperty("ExternalRate")

    private Double externalRate = null;
    @JsonProperty("Currency")

    private String currency = null;
    @JsonProperty("Percentage")

    private Double percentage = null;
    @JsonProperty("Team")

    private OrganisationUnit team = null;
    @JsonProperty("OrganisationUnits")

    private List<OrganisationUnit> organisationUnits = null;
    @JsonProperty("Freelancer")

    private Boolean freelancer = null;
    @JsonProperty("TeamLeader")

    private Boolean teamLeader = null;
    @JsonProperty("DdSystems")

    private Boolean ddSystems = null;
    @JsonProperty("IsManagement")

    private Boolean isManagement = null;
    @JsonProperty("WorkHoursPerDay")

    private Double workHoursPerDay = null;
    @JsonProperty("FteWorkHoursPerDay")

    private Double fteWorkHoursPerDay = null;
    @JsonProperty("Overtime")

    private Double overtime = null;
    @JsonProperty("Holidays")

    private Double holidays = null;
    @JsonProperty("UsePictureOnline")

    private Boolean usePictureOnline = null;
    @JsonProperty("UsePicturePrint")

    private Boolean usePicturePrint = null;
    @JsonProperty("UseVideo")

    private Boolean useVideo = null;
    @JsonProperty("ProfileLink")

    private String profileLink = null;
    @JsonProperty("Notifications")

    private List<EmployeeNotification> notifications = null;
    @JsonProperty("Profiles")

    private List<EmployeeProfile> profiles = null;
    @JsonProperty("PrivateAddress")

    private Address privateAddress = null;
    @JsonProperty("Id")

    private Long id = null;

    public CapabilityExpert experiencePoints(Double experiencePoints) {
        this.experiencePoints = experiencePoints;
        return this;
    }

    /**
     * Get experiencePoints
     *
     * @return experiencePoints
     **/
    @Schema(description = "")
    public Double getExperiencePoints() {
        return experiencePoints;
    }

    public void setExperiencePoints(Double experiencePoints) {
        this.experiencePoints = experiencePoints;
    }

    public CapabilityExpert experienceLevel(ExperienceLevelEnum experienceLevel) {
        this.experienceLevel = experienceLevel;
        return this;
    }

    /**
     * Get experienceLevel
     *
     * @return experienceLevel
     **/
    @Schema(description = "")
    public ExperienceLevelEnum getExperienceLevel() {
        return experienceLevel;
    }

    public void setExperienceLevel(ExperienceLevelEnum experienceLevel) {
        this.experienceLevel = experienceLevel;
    }

    public CapabilityExpert skill(Skill skill) {
        this.skill = skill;
        return this;
    }

    /**
     * Get skill
     *
     * @return skill
     **/
    @Schema(description = "")
    public Skill getSkill() {
        return skill;
    }

    public void setSkill(Skill skill) {
        this.skill = skill;
    }

    public CapabilityExpert vertecId(Long vertecId) {
        this.vertecId = vertecId;
        return this;
    }

    /**
     * Get vertecId
     *
     * @return vertecId
     **/
    @Schema(description = "")
    public Long getVertecId() {
        return vertecId;
    }

    public void setVertecId(Long vertecId) {
        this.vertecId = vertecId;
    }

    public CapabilityExpert code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     *
     * @return code
     **/
    @Schema(description = "")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public CapabilityExpert firstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Get firstName
     *
     * @return firstName
     **/
    @Schema(description = "")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public CapabilityExpert lastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Get lastName
     *
     * @return lastName
     **/
    @Schema(description = "")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Get fullName
     *
     * @return fullName
     **/
    @Schema(description = "")
    public String getFullName() {
        return fullName;
    }

    public CapabilityExpert dateOfBirth(OffsetDateTime dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }

    /**
     * Get dateOfBirth
     *
     * @return dateOfBirth
     **/
    @Schema(description = "")
    public OffsetDateTime getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(OffsetDateTime dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public CapabilityExpert citizenship(String citizenship) {
        this.citizenship = citizenship;
        return this;
    }

    /**
     * Get citizenship
     *
     * @return citizenship
     **/
    @Schema(description = "")
    public String getCitizenship() {
        return citizenship;
    }

    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }

    public CapabilityExpert isOwner(Boolean isOwner) {
        this.isOwner = isOwner;
        return this;
    }

    /**
     * Get isOwner
     *
     * @return isOwner
     **/
    @Schema(description = "")
    public Boolean isIsOwner() {
        return isOwner;
    }

    public void setIsOwner(Boolean isOwner) {
        this.isOwner = isOwner;
    }

    public CapabilityExpert office(Office office) {
        this.office = office;
        return this;
    }

    /**
     * Get office
     *
     * @return office
     **/
    @Schema(description = "")
    public Office getOffice() {
        return office;
    }

    public void setOffice(Office office) {
        this.office = office;
    }

    public CapabilityExpert workingPlace(String workingPlace) {
        this.workingPlace = workingPlace;
        return this;
    }

    /**
     * Get workingPlace
     *
     * @return workingPlace
     **/
    @Schema(description = "")
    public String getWorkingPlace() {
        return workingPlace;
    }

    public void setWorkingPlace(String workingPlace) {
        this.workingPlace = workingPlace;
    }

    public CapabilityExpert description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @Schema(description = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public CapabilityExpert linkedInProfileUrl(String linkedInProfileUrl) {
        this.linkedInProfileUrl = linkedInProfileUrl;
        return this;
    }

    /**
     * Get linkedInProfileUrl
     *
     * @return linkedInProfileUrl
     **/
    @Schema(description = "")
    public String getLinkedInProfileUrl() {
        return linkedInProfileUrl;
    }

    public void setLinkedInProfileUrl(String linkedInProfileUrl) {
        this.linkedInProfileUrl = linkedInProfileUrl;
    }

    public CapabilityExpert xingProfileUrl(String xingProfileUrl) {
        this.xingProfileUrl = xingProfileUrl;
        return this;
    }

    /**
     * Get xingProfileUrl
     *
     * @return xingProfileUrl
     **/
    @Schema(description = "")
    public String getXingProfileUrl() {
        return xingProfileUrl;
    }

    public void setXingProfileUrl(String xingProfileUrl) {
        this.xingProfileUrl = xingProfileUrl;
    }

    public CapabilityExpert twitterProfileUrl(String twitterProfileUrl) {
        this.twitterProfileUrl = twitterProfileUrl;
        return this;
    }

    /**
     * Get twitterProfileUrl
     *
     * @return twitterProfileUrl
     **/
    @Schema(description = "")
    public String getTwitterProfileUrl() {
        return twitterProfileUrl;
    }

    public void setTwitterProfileUrl(String twitterProfileUrl) {
        this.twitterProfileUrl = twitterProfileUrl;
    }

    public CapabilityExpert gitHubUrl(String gitHubUrl) {
        this.gitHubUrl = gitHubUrl;
        return this;
    }

    /**
     * Get gitHubUrl
     *
     * @return gitHubUrl
     **/
    @Schema(description = "")
    public String getGitHubUrl() {
        return gitHubUrl;
    }

    public void setGitHubUrl(String gitHubUrl) {
        this.gitHubUrl = gitHubUrl;
    }

    public CapabilityExpert bitBucketUrl(String bitBucketUrl) {
        this.bitBucketUrl = bitBucketUrl;
        return this;
    }

    /**
     * Get bitBucketUrl
     *
     * @return bitBucketUrl
     **/
    @Schema(description = "")
    public String getBitBucketUrl() {
        return bitBucketUrl;
    }

    public void setBitBucketUrl(String bitBucketUrl) {
        this.bitBucketUrl = bitBucketUrl;
    }

    public CapabilityExpert twitterUrl(String twitterUrl) {
        this.twitterUrl = twitterUrl;
        return this;
    }

    /**
     * Get twitterUrl
     *
     * @return twitterUrl
     **/
    @Schema(description = "")
    public String getTwitterUrl() {
        return twitterUrl;
    }

    public void setTwitterUrl(String twitterUrl) {
        this.twitterUrl = twitterUrl;
    }

    public CapabilityExpert yammerUrl(String yammerUrl) {
        this.yammerUrl = yammerUrl;
        return this;
    }

    /**
     * Get yammerUrl
     *
     * @return yammerUrl
     **/
    @Schema(description = "")
    public String getYammerUrl() {
        return yammerUrl;
    }

    public void setYammerUrl(String yammerUrl) {
        this.yammerUrl = yammerUrl;
    }

    public CapabilityExpert stackoverflowProfileUrl(String stackoverflowProfileUrl) {
        this.stackoverflowProfileUrl = stackoverflowProfileUrl;
        return this;
    }

    /**
     * Get stackoverflowProfileUrl
     *
     * @return stackoverflowProfileUrl
     **/
    @Schema(description = "")
    public String getStackoverflowProfileUrl() {
        return stackoverflowProfileUrl;
    }

    public void setStackoverflowProfileUrl(String stackoverflowProfileUrl) {
        this.stackoverflowProfileUrl = stackoverflowProfileUrl;
    }

    public CapabilityExpert lastUpdated(OffsetDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
        return this;
    }

    /**
     * Get lastUpdated
     *
     * @return lastUpdated
     **/
    @Schema(description = "")
    public OffsetDateTime getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(OffsetDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public CapabilityExpert entryDate(OffsetDateTime entryDate) {
        this.entryDate = entryDate;
        return this;
    }

    /**
     * Get entryDate
     *
     * @return entryDate
     **/
    @Schema(description = "")
    public OffsetDateTime getEntryDate() {
        return entryDate;
    }

    public void setEntryDate(OffsetDateTime entryDate) {
        this.entryDate = entryDate;
    }

    public CapabilityExpert leaveDate(OffsetDateTime leaveDate) {
        this.leaveDate = leaveDate;
        return this;
    }

    /**
     * Get leaveDate
     *
     * @return leaveDate
     **/
    @Schema(description = "")
    public OffsetDateTime getLeaveDate() {
        return leaveDate;
    }

    public void setLeaveDate(OffsetDateTime leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * Get startsIn
     *
     * @return startsIn
     **/
    @Schema(description = "")
    public String getStartsIn() {
        return startsIn;
    }

    /**
     * Get duration
     *
     * @return duration
     **/
    @Schema(description = "")
    public String getDuration() {
        return duration;
    }

    public CapabilityExpert homePhone(String homePhone) {
        this.homePhone = homePhone;
        return this;
    }

    /**
     * Get homePhone
     *
     * @return homePhone
     **/
    @Schema(description = "")
    public String getHomePhone() {
        return homePhone;
    }

    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    public CapabilityExpert mobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
        return this;
    }

    /**
     * Get mobilePhone
     *
     * @return mobilePhone
     **/
    @Schema(description = "")
    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public CapabilityExpert businessPhone(String businessPhone) {
        this.businessPhone = businessPhone;
        return this;
    }

    /**
     * Get businessPhone
     *
     * @return businessPhone
     **/
    @Schema(description = "")
    public String getBusinessPhone() {
        return businessPhone;
    }

    public void setBusinessPhone(String businessPhone) {
        this.businessPhone = businessPhone;
    }

    public CapabilityExpert mail(String mail) {
        this.mail = mail;
        return this;
    }

    /**
     * Get mail
     *
     * @return mail
     **/
    @Schema(description = "")
    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public CapabilityExpert location(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get location
     *
     * @return location
     **/
    @Schema(description = "")
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public CapabilityExpert wants(String wants) {
        this.wants = wants;
        return this;
    }

    /**
     * Get wants
     *
     * @return wants
     **/
    @Schema(description = "")
    public String getWants() {
        return wants;
    }

    public void setWants(String wants) {
        this.wants = wants;
    }

    public CapabilityExpert qualification(Qualification qualification) {
        this.qualification = qualification;
        return this;
    }

    /**
     * Get qualification
     *
     * @return qualification
     **/
    @Schema(description = "")
    public Qualification getQualification() {
        return qualification;
    }

    public void setQualification(Qualification qualification) {
        this.qualification = qualification;
    }

    public CapabilityExpert superior(EmployeeResult superior) {
        this.superior = superior;
        return this;
    }

    /**
     * Get superior
     *
     * @return superior
     **/
    @Schema(description = "")
    public EmployeeResult getSuperior() {
        return superior;
    }

    public void setSuperior(EmployeeResult superior) {
        this.superior = superior;
    }

    public CapabilityExpert jobProfile(JobProfile jobProfile) {
        this.jobProfile = jobProfile;
        return this;
    }

    /**
     * Get jobProfile
     *
     * @return jobProfile
     **/
    @Schema(description = "")
    public JobProfile getJobProfile() {
        return jobProfile;
    }

    public void setJobProfile(JobProfile jobProfile) {
        this.jobProfile = jobProfile;
    }

    public CapabilityExpert title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/
    @Schema(description = "")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public CapabilityExpert graduation(String graduation) {
        this.graduation = graduation;
        return this;
    }

    /**
     * Get graduation
     *
     * @return graduation
     **/
    @Schema(description = "")
    public String getGraduation() {
        return graduation;
    }

    public void setGraduation(String graduation) {
        this.graduation = graduation;
    }

    public CapabilityExpert focus(FocusEnum focus) {
        this.focus = focus;
        return this;
    }

    /**
     * Get focus
     *
     * @return focus
     **/
    @Schema(description = "")
    public FocusEnum getFocus() {
        return focus;
    }

    public void setFocus(FocusEnum focus) {
        this.focus = focus;
    }

    /**
     * Get focusText
     *
     * @return focusText
     **/
    @Schema(description = "")
    public String getFocusText() {
        return focusText;
    }

    public CapabilityExpert assistance(Assistance assistance) {
        this.assistance = assistance;
        return this;
    }

    /**
     * Get assistance
     *
     * @return assistance
     **/
    @Schema(description = "")
    public Assistance getAssistance() {
        return assistance;
    }

    public void setAssistance(Assistance assistance) {
        this.assistance = assistance;
    }

    public CapabilityExpert company(Company company) {
        this.company = company;
        return this;
    }

    /**
     * Get company
     *
     * @return company
     **/
    @Schema(description = "")
    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public CapabilityExpert internalRate(Double internalRate) {
        this.internalRate = internalRate;
        return this;
    }

    /**
     * Get internalRate
     *
     * @return internalRate
     **/
    @Schema(description = "")
    public Double getInternalRate() {
        return internalRate;
    }

    public void setInternalRate(Double internalRate) {
        this.internalRate = internalRate;
    }

    public CapabilityExpert externalRate(Double externalRate) {
        this.externalRate = externalRate;
        return this;
    }

    /**
     * Get externalRate
     *
     * @return externalRate
     **/
    @Schema(description = "")
    public Double getExternalRate() {
        return externalRate;
    }

    public void setExternalRate(Double externalRate) {
        this.externalRate = externalRate;
    }

    public CapabilityExpert currency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     *
     * @return currency
     **/
    @Schema(description = "")
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public CapabilityExpert percentage(Double percentage) {
        this.percentage = percentage;
        return this;
    }

    /**
     * Get percentage
     *
     * @return percentage
     **/
    @Schema(description = "")
    public Double getPercentage() {
        return percentage;
    }

    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }

    public CapabilityExpert team(OrganisationUnit team) {
        this.team = team;
        return this;
    }

    /**
     * Get team
     *
     * @return team
     **/
    @Schema(description = "")
    public OrganisationUnit getTeam() {
        return team;
    }

    public void setTeam(OrganisationUnit team) {
        this.team = team;
    }

    public CapabilityExpert organisationUnits(List<OrganisationUnit> organisationUnits) {
        this.organisationUnits = organisationUnits;
        return this;
    }

    public CapabilityExpert addOrganisationUnitsItem(OrganisationUnit organisationUnitsItem) {
        if (this.organisationUnits == null) {
            this.organisationUnits = new ArrayList<OrganisationUnit>();
        }
        this.organisationUnits.add(organisationUnitsItem);
        return this;
    }

    /**
     * Get organisationUnits
     *
     * @return organisationUnits
     **/
    @Schema(description = "")
    public List<OrganisationUnit> getOrganisationUnits() {
        return organisationUnits;
    }

    public void setOrganisationUnits(List<OrganisationUnit> organisationUnits) {
        this.organisationUnits = organisationUnits;
    }

    public CapabilityExpert freelancer(Boolean freelancer) {
        this.freelancer = freelancer;
        return this;
    }

    /**
     * Get freelancer
     *
     * @return freelancer
     **/
    @Schema(description = "")
    public Boolean isFreelancer() {
        return freelancer;
    }

    public void setFreelancer(Boolean freelancer) {
        this.freelancer = freelancer;
    }

    public CapabilityExpert teamLeader(Boolean teamLeader) {
        this.teamLeader = teamLeader;
        return this;
    }

    /**
     * Get teamLeader
     *
     * @return teamLeader
     **/
    @Schema(description = "")
    public Boolean isTeamLeader() {
        return teamLeader;
    }

    public void setTeamLeader(Boolean teamLeader) {
        this.teamLeader = teamLeader;
    }

    public CapabilityExpert ddSystems(Boolean ddSystems) {
        this.ddSystems = ddSystems;
        return this;
    }

    /**
     * Get ddSystems
     *
     * @return ddSystems
     **/
    @Schema(description = "")
    public Boolean isDdSystems() {
        return ddSystems;
    }

    public void setDdSystems(Boolean ddSystems) {
        this.ddSystems = ddSystems;
    }

    public CapabilityExpert isManagement(Boolean isManagement) {
        this.isManagement = isManagement;
        return this;
    }

    /**
     * Get isManagement
     *
     * @return isManagement
     **/
    @Schema(description = "")
    public Boolean isIsManagement() {
        return isManagement;
    }

    public void setIsManagement(Boolean isManagement) {
        this.isManagement = isManagement;
    }

    public CapabilityExpert workHoursPerDay(Double workHoursPerDay) {
        this.workHoursPerDay = workHoursPerDay;
        return this;
    }

    /**
     * Get workHoursPerDay
     *
     * @return workHoursPerDay
     **/
    @Schema(description = "")
    public Double getWorkHoursPerDay() {
        return workHoursPerDay;
    }

    public void setWorkHoursPerDay(Double workHoursPerDay) {
        this.workHoursPerDay = workHoursPerDay;
    }

    public CapabilityExpert fteWorkHoursPerDay(Double fteWorkHoursPerDay) {
        this.fteWorkHoursPerDay = fteWorkHoursPerDay;
        return this;
    }

    /**
     * Get fteWorkHoursPerDay
     *
     * @return fteWorkHoursPerDay
     **/
    @Schema(description = "")
    public Double getFteWorkHoursPerDay() {
        return fteWorkHoursPerDay;
    }

    public void setFteWorkHoursPerDay(Double fteWorkHoursPerDay) {
        this.fteWorkHoursPerDay = fteWorkHoursPerDay;
    }

    public CapabilityExpert overtime(Double overtime) {
        this.overtime = overtime;
        return this;
    }

    /**
     * Get overtime
     *
     * @return overtime
     **/
    @Schema(description = "")
    public Double getOvertime() {
        return overtime;
    }

    public void setOvertime(Double overtime) {
        this.overtime = overtime;
    }

    public CapabilityExpert holidays(Double holidays) {
        this.holidays = holidays;
        return this;
    }

    /**
     * Get holidays
     *
     * @return holidays
     **/
    @Schema(description = "")
    public Double getHolidays() {
        return holidays;
    }

    public void setHolidays(Double holidays) {
        this.holidays = holidays;
    }

    public CapabilityExpert usePictureOnline(Boolean usePictureOnline) {
        this.usePictureOnline = usePictureOnline;
        return this;
    }

    /**
     * Get usePictureOnline
     *
     * @return usePictureOnline
     **/
    @Schema(description = "")
    public Boolean isUsePictureOnline() {
        return usePictureOnline;
    }

    public void setUsePictureOnline(Boolean usePictureOnline) {
        this.usePictureOnline = usePictureOnline;
    }

    public CapabilityExpert usePicturePrint(Boolean usePicturePrint) {
        this.usePicturePrint = usePicturePrint;
        return this;
    }

    /**
     * Get usePicturePrint
     *
     * @return usePicturePrint
     **/
    @Schema(description = "")
    public Boolean isUsePicturePrint() {
        return usePicturePrint;
    }

    public void setUsePicturePrint(Boolean usePicturePrint) {
        this.usePicturePrint = usePicturePrint;
    }

    public CapabilityExpert useVideo(Boolean useVideo) {
        this.useVideo = useVideo;
        return this;
    }

    /**
     * Get useVideo
     *
     * @return useVideo
     **/
    @Schema(description = "")
    public Boolean isUseVideo() {
        return useVideo;
    }

    public void setUseVideo(Boolean useVideo) {
        this.useVideo = useVideo;
    }

    public CapabilityExpert profileLink(String profileLink) {
        this.profileLink = profileLink;
        return this;
    }

    /**
     * Get profileLink
     *
     * @return profileLink
     **/
    @Schema(description = "")
    public String getProfileLink() {
        return profileLink;
    }

    public void setProfileLink(String profileLink) {
        this.profileLink = profileLink;
    }

    /**
     * Get notifications
     *
     * @return notifications
     **/
    @Schema(description = "")
    public List<EmployeeNotification> getNotifications() {
        return notifications;
    }

    public CapabilityExpert profiles(List<EmployeeProfile> profiles) {
        this.profiles = profiles;
        return this;
    }

    public CapabilityExpert addProfilesItem(EmployeeProfile profilesItem) {
        if (this.profiles == null) {
            this.profiles = new ArrayList<EmployeeProfile>();
        }
        this.profiles.add(profilesItem);
        return this;
    }

    /**
     * Get profiles
     *
     * @return profiles
     **/
    @Schema(description = "")
    public List<EmployeeProfile> getProfiles() {
        return profiles;
    }

    public void setProfiles(List<EmployeeProfile> profiles) {
        this.profiles = profiles;
    }

    public CapabilityExpert privateAddress(Address privateAddress) {
        this.privateAddress = privateAddress;
        return this;
    }

    /**
     * Get privateAddress
     *
     * @return privateAddress
     **/
    @Schema(description = "")
    public Address getPrivateAddress() {
        return privateAddress;
    }

    public void setPrivateAddress(Address privateAddress) {
        this.privateAddress = privateAddress;
    }

    public CapabilityExpert id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CapabilityExpert capabilityExpert = (CapabilityExpert) o;
        return Objects.equals(this.experiencePoints, capabilityExpert.experiencePoints) &&
                Objects.equals(this.experienceLevel, capabilityExpert.experienceLevel) &&
                Objects.equals(this.skill, capabilityExpert.skill) &&
                Objects.equals(this.vertecId, capabilityExpert.vertecId) &&
                Objects.equals(this.code, capabilityExpert.code) &&
                Objects.equals(this.firstName, capabilityExpert.firstName) &&
                Objects.equals(this.lastName, capabilityExpert.lastName) &&
                Objects.equals(this.fullName, capabilityExpert.fullName) &&
                Objects.equals(this.dateOfBirth, capabilityExpert.dateOfBirth) &&
                Objects.equals(this.citizenship, capabilityExpert.citizenship) &&
                Objects.equals(this.isOwner, capabilityExpert.isOwner) &&
                Objects.equals(this.office, capabilityExpert.office) &&
                Objects.equals(this.workingPlace, capabilityExpert.workingPlace) &&
                Objects.equals(this.description, capabilityExpert.description) &&
                Objects.equals(this.linkedInProfileUrl, capabilityExpert.linkedInProfileUrl) &&
                Objects.equals(this.xingProfileUrl, capabilityExpert.xingProfileUrl) &&
                Objects.equals(this.twitterProfileUrl, capabilityExpert.twitterProfileUrl) &&
                Objects.equals(this.gitHubUrl, capabilityExpert.gitHubUrl) &&
                Objects.equals(this.bitBucketUrl, capabilityExpert.bitBucketUrl) &&
                Objects.equals(this.twitterUrl, capabilityExpert.twitterUrl) &&
                Objects.equals(this.yammerUrl, capabilityExpert.yammerUrl) &&
                Objects.equals(this.stackoverflowProfileUrl, capabilityExpert.stackoverflowProfileUrl) &&
                Objects.equals(this.lastUpdated, capabilityExpert.lastUpdated) &&
                Objects.equals(this.entryDate, capabilityExpert.entryDate) &&
                Objects.equals(this.leaveDate, capabilityExpert.leaveDate) &&
                Objects.equals(this.startsIn, capabilityExpert.startsIn) &&
                Objects.equals(this.duration, capabilityExpert.duration) &&
                Objects.equals(this.homePhone, capabilityExpert.homePhone) &&
                Objects.equals(this.mobilePhone, capabilityExpert.mobilePhone) &&
                Objects.equals(this.businessPhone, capabilityExpert.businessPhone) &&
                Objects.equals(this.mail, capabilityExpert.mail) &&
                Objects.equals(this.location, capabilityExpert.location) &&
                Objects.equals(this.wants, capabilityExpert.wants) &&
                Objects.equals(this.qualification, capabilityExpert.qualification) &&
                Objects.equals(this.superior, capabilityExpert.superior) &&
                Objects.equals(this.jobProfile, capabilityExpert.jobProfile) &&
                Objects.equals(this.title, capabilityExpert.title) &&
                Objects.equals(this.graduation, capabilityExpert.graduation) &&
                Objects.equals(this.focus, capabilityExpert.focus) &&
                Objects.equals(this.focusText, capabilityExpert.focusText) &&
                Objects.equals(this.assistance, capabilityExpert.assistance) &&
                Objects.equals(this.company, capabilityExpert.company) &&
                Objects.equals(this.internalRate, capabilityExpert.internalRate) &&
                Objects.equals(this.externalRate, capabilityExpert.externalRate) &&
                Objects.equals(this.currency, capabilityExpert.currency) &&
                Objects.equals(this.percentage, capabilityExpert.percentage) &&
                Objects.equals(this.team, capabilityExpert.team) &&
                Objects.equals(this.organisationUnits, capabilityExpert.organisationUnits) &&
                Objects.equals(this.freelancer, capabilityExpert.freelancer) &&
                Objects.equals(this.teamLeader, capabilityExpert.teamLeader) &&
                Objects.equals(this.ddSystems, capabilityExpert.ddSystems) &&
                Objects.equals(this.isManagement, capabilityExpert.isManagement) &&
                Objects.equals(this.workHoursPerDay, capabilityExpert.workHoursPerDay) &&
                Objects.equals(this.fteWorkHoursPerDay, capabilityExpert.fteWorkHoursPerDay) &&
                Objects.equals(this.overtime, capabilityExpert.overtime) &&
                Objects.equals(this.holidays, capabilityExpert.holidays) &&
                Objects.equals(this.usePictureOnline, capabilityExpert.usePictureOnline) &&
                Objects.equals(this.usePicturePrint, capabilityExpert.usePicturePrint) &&
                Objects.equals(this.useVideo, capabilityExpert.useVideo) &&
                Objects.equals(this.profileLink, capabilityExpert.profileLink) &&
                Objects.equals(this.notifications, capabilityExpert.notifications) &&
                Objects.equals(this.profiles, capabilityExpert.profiles) &&
                Objects.equals(this.privateAddress, capabilityExpert.privateAddress) &&
                Objects.equals(this.id, capabilityExpert.id);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(experiencePoints, experienceLevel, skill, vertecId, code, firstName, lastName, fullName, dateOfBirth, citizenship, isOwner, office, workingPlace, description, linkedInProfileUrl, xingProfileUrl, twitterProfileUrl, gitHubUrl, bitBucketUrl, twitterUrl, yammerUrl, stackoverflowProfileUrl, lastUpdated, entryDate, leaveDate, startsIn, duration, homePhone, mobilePhone, businessPhone, mail, location, wants, qualification, superior, jobProfile, title, graduation, focus, focusText, assistance, company, internalRate, externalRate, currency, percentage, team, organisationUnits, freelancer, teamLeader, ddSystems, isManagement, workHoursPerDay, fteWorkHoursPerDay, overtime, holidays, usePictureOnline, usePicturePrint, useVideo, profileLink, notifications, profiles, privateAddress, id);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CapabilityExpert {\n");

        sb.append("    experiencePoints: ").append(toIndentedString(experiencePoints)).append("\n");
        sb.append("    experienceLevel: ").append(toIndentedString(experienceLevel)).append("\n");
        sb.append("    skill: ").append(toIndentedString(skill)).append("\n");
        sb.append("    vertecId: ").append(toIndentedString(vertecId)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
        sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
        sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
        sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
        sb.append("    citizenship: ").append(toIndentedString(citizenship)).append("\n");
        sb.append("    isOwner: ").append(toIndentedString(isOwner)).append("\n");
        sb.append("    office: ").append(toIndentedString(office)).append("\n");
        sb.append("    workingPlace: ").append(toIndentedString(workingPlace)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    linkedInProfileUrl: ").append(toIndentedString(linkedInProfileUrl)).append("\n");
        sb.append("    xingProfileUrl: ").append(toIndentedString(xingProfileUrl)).append("\n");
        sb.append("    twitterProfileUrl: ").append(toIndentedString(twitterProfileUrl)).append("\n");
        sb.append("    gitHubUrl: ").append(toIndentedString(gitHubUrl)).append("\n");
        sb.append("    bitBucketUrl: ").append(toIndentedString(bitBucketUrl)).append("\n");
        sb.append("    twitterUrl: ").append(toIndentedString(twitterUrl)).append("\n");
        sb.append("    yammerUrl: ").append(toIndentedString(yammerUrl)).append("\n");
        sb.append("    stackoverflowProfileUrl: ").append(toIndentedString(stackoverflowProfileUrl)).append("\n");
        sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
        sb.append("    entryDate: ").append(toIndentedString(entryDate)).append("\n");
        sb.append("    leaveDate: ").append(toIndentedString(leaveDate)).append("\n");
        sb.append("    startsIn: ").append(toIndentedString(startsIn)).append("\n");
        sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
        sb.append("    homePhone: ").append(toIndentedString(homePhone)).append("\n");
        sb.append("    mobilePhone: ").append(toIndentedString(mobilePhone)).append("\n");
        sb.append("    businessPhone: ").append(toIndentedString(businessPhone)).append("\n");
        sb.append("    mail: ").append(toIndentedString(mail)).append("\n");
        sb.append("    location: ").append(toIndentedString(location)).append("\n");
        sb.append("    wants: ").append(toIndentedString(wants)).append("\n");
        sb.append("    qualification: ").append(toIndentedString(qualification)).append("\n");
        sb.append("    superior: ").append(toIndentedString(superior)).append("\n");
        sb.append("    jobProfile: ").append(toIndentedString(jobProfile)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    graduation: ").append(toIndentedString(graduation)).append("\n");
        sb.append("    focus: ").append(toIndentedString(focus)).append("\n");
        sb.append("    focusText: ").append(toIndentedString(focusText)).append("\n");
        sb.append("    assistance: ").append(toIndentedString(assistance)).append("\n");
        sb.append("    company: ").append(toIndentedString(company)).append("\n");
        sb.append("    internalRate: ").append(toIndentedString(internalRate)).append("\n");
        sb.append("    externalRate: ").append(toIndentedString(externalRate)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
        sb.append("    team: ").append(toIndentedString(team)).append("\n");
        sb.append("    organisationUnits: ").append(toIndentedString(organisationUnits)).append("\n");
        sb.append("    freelancer: ").append(toIndentedString(freelancer)).append("\n");
        sb.append("    teamLeader: ").append(toIndentedString(teamLeader)).append("\n");
        sb.append("    ddSystems: ").append(toIndentedString(ddSystems)).append("\n");
        sb.append("    isManagement: ").append(toIndentedString(isManagement)).append("\n");
        sb.append("    workHoursPerDay: ").append(toIndentedString(workHoursPerDay)).append("\n");
        sb.append("    fteWorkHoursPerDay: ").append(toIndentedString(fteWorkHoursPerDay)).append("\n");
        sb.append("    overtime: ").append(toIndentedString(overtime)).append("\n");
        sb.append("    holidays: ").append(toIndentedString(holidays)).append("\n");
        sb.append("    usePictureOnline: ").append(toIndentedString(usePictureOnline)).append("\n");
        sb.append("    usePicturePrint: ").append(toIndentedString(usePicturePrint)).append("\n");
        sb.append("    useVideo: ").append(toIndentedString(useVideo)).append("\n");
        sb.append("    profileLink: ").append(toIndentedString(profileLink)).append("\n");
        sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
        sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
        sb.append("    privateAddress: ").append(toIndentedString(privateAddress)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets experienceLevel
     */
    public enum ExperienceLevelEnum {
        NUMBER_0(0),
        NUMBER_1(1),
        NUMBER_2(2),
        NUMBER_4(4),
        NUMBER_5(5),
        NUMBER_6(6);

        private Integer value;

        ExperienceLevelEnum(Integer value) {
            this.value = value;
        }

        @JsonCreator
        public static ExperienceLevelEnum fromValue(String text) {
            for (ExperienceLevelEnum b : ExperienceLevelEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @JsonValue
        public Integer getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

    }

    /**
     * Gets or Sets focus
     */
    public enum FocusEnum {
        NUMBER_0(0),
        NUMBER_1(1),
        NUMBER_2(2);

        private Integer value;

        FocusEnum(Integer value) {
            this.value = value;
        }

        @JsonCreator
        public static FocusEnum fromValue(String text) {
            for (FocusEnum b : FocusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @JsonValue
        public Integer getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

    }

}
