/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.zuehlke.fullstack.ConnectZuehlke.apis.insight.dto.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Capability
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T13:18:19.970506+01:00[Europe/Zurich]")
public class Capability {

    @JsonProperty("Id")

    private Long id = null;

    @JsonProperty("Name")

    private String name = null;

    @JsonProperty("ShortDescription")

    private String shortDescription = null;

    @JsonProperty("GroupName")

    private String groupName = null;

    @JsonProperty("Description")

    private String description = null;

    @JsonProperty("Activities")

    private String activities = null;

    @JsonProperty("TrendSummary")

    private String trendSummary = null;

    @JsonProperty("SortOrder")

    private Integer sortOrder = null;

    @JsonProperty("JobProfileAffinities")

    private List<JobProfileAffinity> jobProfileAffinities = null;

    @JsonProperty("Deliverables")

    private List<Deliverable> deliverables = null;

    @JsonProperty("Employees")

    private List<CapabilityEmployee> employees = null;

    public Capability id(Long id) {
        this.id = id;
        return this;
    }


    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Capability name(String name) {
        this.name = name;
        return this;
    }


    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Capability shortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
        return this;
    }


    /**
     * Get shortDescription
     *
     * @return shortDescription
     **/
    @Schema(description = "")
    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public Capability groupName(String groupName) {
        this.groupName = groupName;
        return this;
    }


    /**
     * Get groupName
     *
     * @return groupName
     **/
    @Schema(description = "")
    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Capability description(String description) {
        this.description = description;
        return this;
    }


    /**
     * Get description
     *
     * @return description
     **/
    @Schema(description = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Capability activities(String activities) {
        this.activities = activities;
        return this;
    }


    /**
     * Get activities
     *
     * @return activities
     **/
    @Schema(description = "")
    public String getActivities() {
        return activities;
    }

    public void setActivities(String activities) {
        this.activities = activities;
    }

    public Capability trendSummary(String trendSummary) {
        this.trendSummary = trendSummary;
        return this;
    }


    /**
     * Get trendSummary
     *
     * @return trendSummary
     **/
    @Schema(description = "")
    public String getTrendSummary() {
        return trendSummary;
    }

    public void setTrendSummary(String trendSummary) {
        this.trendSummary = trendSummary;
    }

    public Capability sortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }


    /**
     * Get sortOrder
     *
     * @return sortOrder
     **/
    @Schema(description = "")
    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Capability jobProfileAffinities(List<JobProfileAffinity> jobProfileAffinities) {
        this.jobProfileAffinities = jobProfileAffinities;
        return this;
    }

    public Capability addJobProfileAffinitiesItem(JobProfileAffinity jobProfileAffinitiesItem) {
        if (this.jobProfileAffinities == null) {
            this.jobProfileAffinities = new ArrayList<JobProfileAffinity>();
        }
        this.jobProfileAffinities.add(jobProfileAffinitiesItem);
        return this;
    }

    /**
     * Get jobProfileAffinities
     *
     * @return jobProfileAffinities
     **/
    @Schema(description = "")
    public List<JobProfileAffinity> getJobProfileAffinities() {
        return jobProfileAffinities;
    }

    public void setJobProfileAffinities(List<JobProfileAffinity> jobProfileAffinities) {
        this.jobProfileAffinities = jobProfileAffinities;
    }

    public Capability deliverables(List<Deliverable> deliverables) {
        this.deliverables = deliverables;
        return this;
    }

    public Capability addDeliverablesItem(Deliverable deliverablesItem) {
        if (this.deliverables == null) {
            this.deliverables = new ArrayList<Deliverable>();
        }
        this.deliverables.add(deliverablesItem);
        return this;
    }

    /**
     * Get deliverables
     *
     * @return deliverables
     **/
    @Schema(description = "")
    public List<Deliverable> getDeliverables() {
        return deliverables;
    }

    public void setDeliverables(List<Deliverable> deliverables) {
        this.deliverables = deliverables;
    }

    public Capability employees(List<CapabilityEmployee> employees) {
        this.employees = employees;
        return this;
    }

    public Capability addEmployeesItem(CapabilityEmployee employeesItem) {
        if (this.employees == null) {
            this.employees = new ArrayList<CapabilityEmployee>();
        }
        this.employees.add(employeesItem);
        return this;
    }

    /**
     * Get employees
     *
     * @return employees
     **/
    @Schema(description = "")
    public List<CapabilityEmployee> getEmployees() {
        return employees;
    }

    public void setEmployees(List<CapabilityEmployee> employees) {
        this.employees = employees;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Capability capability = (Capability) o;
        return Objects.equals(this.id, capability.id) &&
                Objects.equals(this.name, capability.name) &&
                Objects.equals(this.shortDescription, capability.shortDescription) &&
                Objects.equals(this.groupName, capability.groupName) &&
                Objects.equals(this.description, capability.description) &&
                Objects.equals(this.activities, capability.activities) &&
                Objects.equals(this.trendSummary, capability.trendSummary) &&
                Objects.equals(this.sortOrder, capability.sortOrder) &&
                Objects.equals(this.jobProfileAffinities, capability.jobProfileAffinities) &&
                Objects.equals(this.deliverables, capability.deliverables) &&
                Objects.equals(this.employees, capability.employees);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, name, shortDescription, groupName, description, activities, trendSummary, sortOrder, jobProfileAffinities, deliverables, employees);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Capability {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
        sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    activities: ").append(toIndentedString(activities)).append("\n");
        sb.append("    trendSummary: ").append(toIndentedString(trendSummary)).append("\n");
        sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
        sb.append("    jobProfileAffinities: ").append(toIndentedString(jobProfileAffinities)).append("\n");
        sb.append("    deliverables: ").append(toIndentedString(deliverables)).append("\n");
        sb.append("    employees: ").append(toIndentedString(employees)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
