/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.zuehlke.fullstack.ConnectZuehlke.apis.insight.dto.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * JobProfileAffinity
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T13:18:19.970506+01:00[Europe/Zurich]")
public class JobProfileAffinity {

    @JsonProperty("JobProfile")

    private JobProfile jobProfile = null;
    @JsonProperty("ExperienceLevel")

    private ExperienceLevelEnum experienceLevel = null;

    public JobProfileAffinity jobProfile(JobProfile jobProfile) {
        this.jobProfile = jobProfile;
        return this;
    }

    /**
     * Get jobProfile
     *
     * @return jobProfile
     **/
    @Schema(description = "")
    public JobProfile getJobProfile() {
        return jobProfile;
    }

    public void setJobProfile(JobProfile jobProfile) {
        this.jobProfile = jobProfile;
    }

    public JobProfileAffinity experienceLevel(ExperienceLevelEnum experienceLevel) {
        this.experienceLevel = experienceLevel;
        return this;
    }

    /**
     * Get experienceLevel
     *
     * @return experienceLevel
     **/
    @Schema(description = "")
    public ExperienceLevelEnum getExperienceLevel() {
        return experienceLevel;
    }

    public void setExperienceLevel(ExperienceLevelEnum experienceLevel) {
        this.experienceLevel = experienceLevel;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobProfileAffinity jobProfileAffinity = (JobProfileAffinity) o;
        return Objects.equals(this.jobProfile, jobProfileAffinity.jobProfile) &&
                Objects.equals(this.experienceLevel, jobProfileAffinity.experienceLevel);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(jobProfile, experienceLevel);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobProfileAffinity {\n");

        sb.append("    jobProfile: ").append(toIndentedString(jobProfile)).append("\n");
        sb.append("    experienceLevel: ").append(toIndentedString(experienceLevel)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets experienceLevel
     */
    public enum ExperienceLevelEnum {
        NUMBER_0(0),
        NUMBER_1(1),
        NUMBER_2(2),
        NUMBER_4(4),
        NUMBER_5(5),
        NUMBER_6(6);

        private Integer value;

        ExperienceLevelEnum(Integer value) {
            this.value = value;
        }

        @JsonCreator
        public static ExperienceLevelEnum fromValue(String text) {
            for (ExperienceLevelEnum b : ExperienceLevelEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @JsonValue
        public Integer getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

    }

}
