/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.zuehlke.fullstack.ConnectZuehlke.apis.insight.dto.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * MediaAssetVote
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T13:18:19.970506+01:00[Europe/Zurich]")
public class MediaAssetVote {

    @JsonProperty("Id")

    private Long id = null;

    @JsonProperty("EmployeeId")

    private Long employeeId = null;

    @JsonProperty("MediaAssetId")

    private Long mediaAssetId = null;

    @JsonProperty("Vote")

    private Boolean vote = null;

    public MediaAssetVote id(Long id) {
        this.id = id;
        return this;
    }


    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MediaAssetVote employeeId(Long employeeId) {
        this.employeeId = employeeId;
        return this;
    }


    /**
     * Get employeeId
     *
     * @return employeeId
     **/
    @Schema(description = "")
    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public MediaAssetVote mediaAssetId(Long mediaAssetId) {
        this.mediaAssetId = mediaAssetId;
        return this;
    }


    /**
     * Get mediaAssetId
     *
     * @return mediaAssetId
     **/
    @Schema(description = "")
    public Long getMediaAssetId() {
        return mediaAssetId;
    }

    public void setMediaAssetId(Long mediaAssetId) {
        this.mediaAssetId = mediaAssetId;
    }

    public MediaAssetVote vote(Boolean vote) {
        this.vote = vote;
        return this;
    }


    /**
     * Get vote
     *
     * @return vote
     **/
    @Schema(description = "")
    public Boolean isVote() {
        return vote;
    }

    public void setVote(Boolean vote) {
        this.vote = vote;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MediaAssetVote mediaAssetVote = (MediaAssetVote) o;
        return Objects.equals(this.id, mediaAssetVote.id) &&
                Objects.equals(this.employeeId, mediaAssetVote.employeeId) &&
                Objects.equals(this.mediaAssetId, mediaAssetVote.mediaAssetId) &&
                Objects.equals(this.vote, mediaAssetVote.vote);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, employeeId, mediaAssetId, vote);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MediaAssetVote {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
        sb.append("    mediaAssetId: ").append(toIndentedString(mediaAssetId)).append("\n");
        sb.append("    vote: ").append(toIndentedString(vote)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
