/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.zuehlke.fullstack.ConnectZuehlke.apis.insight.dto.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ShortProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T13:18:19.970506+01:00[Europe/Zurich]")
public class ShortProfile {

    @JsonProperty("Id")

    private Long id = null;

    @JsonProperty("Role")

    private String role = null;

    @JsonProperty("SortOrder")

    private Integer sortOrder = null;

    @JsonProperty("DescriptionDe")

    private String descriptionDe = null;

    @JsonProperty("DescriptionEn")

    private String descriptionEn = null;
    @JsonProperty("ReleaseStateDe")

    private ReleaseStateDeEnum releaseStateDe = null;
    @JsonProperty("ReleaseStateEn")

    private ReleaseStateEnEnum releaseStateEn = null;
    @JsonProperty("Employee")

    private EmployeeResult employee = null;

    public ShortProfile id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ShortProfile role(String role) {
        this.role = role;
        return this;
    }

    /**
     * Get role
     *
     * @return role
     **/
    @Schema(description = "")
    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public ShortProfile sortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }

    /**
     * Get sortOrder
     *
     * @return sortOrder
     **/
    @Schema(description = "")
    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public ShortProfile descriptionDe(String descriptionDe) {
        this.descriptionDe = descriptionDe;
        return this;
    }

    /**
     * Get descriptionDe
     *
     * @return descriptionDe
     **/
    @Schema(description = "")
    public String getDescriptionDe() {
        return descriptionDe;
    }

    public void setDescriptionDe(String descriptionDe) {
        this.descriptionDe = descriptionDe;
    }

    public ShortProfile descriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
        return this;
    }

    /**
     * Get descriptionEn
     *
     * @return descriptionEn
     **/
    @Schema(description = "")
    public String getDescriptionEn() {
        return descriptionEn;
    }

    public void setDescriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
    }

    public ShortProfile releaseStateDe(ReleaseStateDeEnum releaseStateDe) {
        this.releaseStateDe = releaseStateDe;
        return this;
    }

    /**
     * Get releaseStateDe
     *
     * @return releaseStateDe
     **/
    @Schema(description = "")
    public ReleaseStateDeEnum getReleaseStateDe() {
        return releaseStateDe;
    }

    public void setReleaseStateDe(ReleaseStateDeEnum releaseStateDe) {
        this.releaseStateDe = releaseStateDe;
    }

    public ShortProfile releaseStateEn(ReleaseStateEnEnum releaseStateEn) {
        this.releaseStateEn = releaseStateEn;
        return this;
    }

    /**
     * Get releaseStateEn
     *
     * @return releaseStateEn
     **/
    @Schema(description = "")
    public ReleaseStateEnEnum getReleaseStateEn() {
        return releaseStateEn;
    }

    public void setReleaseStateEn(ReleaseStateEnEnum releaseStateEn) {
        this.releaseStateEn = releaseStateEn;
    }

    public ShortProfile employee(EmployeeResult employee) {
        this.employee = employee;
        return this;
    }

    /**
     * Get employee
     *
     * @return employee
     **/
    @Schema(description = "")
    public EmployeeResult getEmployee() {
        return employee;
    }

    public void setEmployee(EmployeeResult employee) {
        this.employee = employee;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShortProfile shortProfile = (ShortProfile) o;
        return Objects.equals(this.id, shortProfile.id) &&
                Objects.equals(this.role, shortProfile.role) &&
                Objects.equals(this.sortOrder, shortProfile.sortOrder) &&
                Objects.equals(this.descriptionDe, shortProfile.descriptionDe) &&
                Objects.equals(this.descriptionEn, shortProfile.descriptionEn) &&
                Objects.equals(this.releaseStateDe, shortProfile.releaseStateDe) &&
                Objects.equals(this.releaseStateEn, shortProfile.releaseStateEn) &&
                Objects.equals(this.employee, shortProfile.employee);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, role, sortOrder, descriptionDe, descriptionEn, releaseStateDe, releaseStateEn, employee);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ShortProfile {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
        sb.append("    descriptionDe: ").append(toIndentedString(descriptionDe)).append("\n");
        sb.append("    descriptionEn: ").append(toIndentedString(descriptionEn)).append("\n");
        sb.append("    releaseStateDe: ").append(toIndentedString(releaseStateDe)).append("\n");
        sb.append("    releaseStateEn: ").append(toIndentedString(releaseStateEn)).append("\n");
        sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets releaseStateDe
     */
    public enum ReleaseStateDeEnum {
        NUMBER_0(0),
        NUMBER_1(1),
        NUMBER_2(2);

        private Integer value;

        ReleaseStateDeEnum(Integer value) {
            this.value = value;
        }

        @JsonCreator
        public static ReleaseStateDeEnum fromValue(String text) {
            for (ReleaseStateDeEnum b : ReleaseStateDeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @JsonValue
        public Integer getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

    }

    /**
     * Gets or Sets releaseStateEn
     */
    public enum ReleaseStateEnEnum {
        NUMBER_0(0),
        NUMBER_1(1),
        NUMBER_2(2);

        private Integer value;

        ReleaseStateEnEnum(Integer value) {
            this.value = value;
        }

        @JsonCreator
        public static ReleaseStateEnEnum fromValue(String text) {
            for (ReleaseStateEnEnum b : ReleaseStateEnEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @JsonValue
        public Integer getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

    }

}
