/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.zuehlke.fullstack.ConnectZuehlke.apis.insight.dto.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * TrainingParticipationSource
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-03-21T13:18:19.970506+01:00[Europe/Zurich]")
public class TrainingParticipationSource {

    @JsonProperty("Id")

    private Long id = null;

    @JsonProperty("ImportName")

    private String importName = null;
    @JsonProperty("Source")

    private SourceEnum source = null;
    @JsonProperty("SourceText")

    private String sourceText = null;

    public TrainingParticipationSource id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public TrainingParticipationSource importName(String importName) {
        this.importName = importName;
        return this;
    }

    /**
     * Get importName
     *
     * @return importName
     **/
    @Schema(description = "")
    public String getImportName() {
        return importName;
    }

    public void setImportName(String importName) {
        this.importName = importName;
    }

    public TrainingParticipationSource source(SourceEnum source) {
        this.source = source;
        return this;
    }

    /**
     * Get source
     *
     * @return source
     **/
    @Schema(description = "")
    public SourceEnum getSource() {
        return source;
    }

    public void setSource(SourceEnum source) {
        this.source = source;
    }

    /**
     * Get sourceText
     *
     * @return sourceText
     **/
    @Schema(description = "")
    public String getSourceText() {
        return sourceText;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TrainingParticipationSource trainingParticipationSource = (TrainingParticipationSource) o;
        return Objects.equals(this.id, trainingParticipationSource.id) &&
                Objects.equals(this.importName, trainingParticipationSource.importName) &&
                Objects.equals(this.source, trainingParticipationSource.source) &&
                Objects.equals(this.sourceText, trainingParticipationSource.sourceText);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(id, importName, source, sourceText);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TrainingParticipationSource {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    importName: ").append(toIndentedString(importName)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    sourceText: ").append(toIndentedString(sourceText)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets source
     */
    public enum SourceEnum {
        NUMBER_0(0),
        NUMBER_1(1),
        NUMBER_2(2),
        NUMBER_3(3),
        NUMBER_4(4),
        NUMBER_5(5),
        NUMBER_6(6);

        private Integer value;

        SourceEnum(Integer value) {
            this.value = value;
        }

        @JsonCreator
        public static SourceEnum fromValue(String text) {
            for (SourceEnum b : SourceEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @JsonValue
        public Integer getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

    }

}
